spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_farm
    username: postgres
    password: Mose@198
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: ${PORT:8080}